### ISSUE TITLE
 Failed to connect using Cloud + Local

### ISSUE THREAD

**Issue by style6** [libdyson-wg/ha-dyson#25]
tp04 device unavailable
![2023524-01127](https://github.com/libdyson-wg/ha-dyson/assets/47061418/db01b646-1c07-47e5-89ad-279876eb02cb)
![2023524-01242](https://github.com/libdyson-wg/ha-dyson/assets/47061418/94a5b6e1-5565-46d8-8f77-e88d17f3bf3d)

**Comment by dotvezz** [comment]
I just released [v0.21.0](https://github.com/libdyson-wg/ha-dyson/releases/tag/v0.21.0) which may addresses this (I'm not sure, but curious)! Let me know if you have any issues.

**Comment by jcboliveira** [comment]
Still happens however the solution (found in another post)  logout form Dyson app and add everything (cloud +local) worked
